- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Install multiple packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - http-present
        - php
        - mysql
